name: C/C++ CI

on:
  push:
    branches: [ "a21snsxx-user-12-SP1A.210812.016-A217FXXU8DVF6-release-keys" ]
  pull_request:
    branches: [ "a21snsxx-user-12-SP1A.210812.016-A217FXXU8DVF6-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
